# Generated by Django 4.1.3 on 2022-11-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_enterprise',
            field=models.BooleanField(default=False, verbose_name='enterprise status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=False, verbose_name='patient status'),
        ),
    ]
