# Generated by Django 4.1.3 on 2022-11-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('blood_pressure', models.IntegerField(blank=True, null=True)),
                ('sugar_level', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bodyfat', models.IntegerField(blank=True, null=True)),
                ('diastolic', models.IntegerField(blank=True, null=True)),
                ('systolic', models.IntegerField(blank=True, null=True)),
                ('gripForce', models.IntegerField(blank=True, null=True)),
                ('situps_count', models.IntegerField(blank=True, null=True)),
                ('sit_bend_forward', models.IntegerField(blank=True, null=True)),
                ('broadjump_cm', models.IntegerField(blank=True, null=True)),
                ('outcome', models.IntegerField(blank=True, null=True)),
                ('bmi', models.IntegerField(blank=True, null=True)),
                ('pregnancy', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
            ],
        ),
    ]
