# Generated by Django 4.1.3 on 2022-11-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyvitals',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='bodyfat',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='broadjump_cm',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='gripForce',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='sit_bend_forward',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='situps_count',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='sugar_level',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='temperature',
        ),
    ]
