# Generated by Django 4.1.3 on 2022-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyvitals',
            old_name='age',
            new_name='heart_rate',
        ),
        migrations.RenameField(
            model_name='dailyvitals',
            old_name='blood_pressure',
            new_name='steps',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='bodyfat',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='broadjump_cm',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='diastolic',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='gripForce',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='height',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='sit_bend_forward',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='situps_count',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='sugar_level',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='systolic',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='dailyvitals',
            name='weight',
        ),
        migrations.AddField(
            model_name='dailyvitals',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyvitals',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
